apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: glusterfs-pvc
 namespace: library # specify your own namespace
 annotations:
   volume.beta.kubernetes.io/storage-class: gluster-heketi
spec:
 accessModes:
  - ReadWriteOnce
 resources:
   requests:
     storage: 95Gi # specific storage size less that glusterfs cluster size, you can use `heketi-cli topology info` to check glusterfs cluster size in heketi server.

